# Commented lines that are ignored starte with the '#' mark.
# # A helpful tutorial for more information on make
# # https://www.cs.swarthmore.edu/~newhall/unixhelp/howto_makefiles.html

all :
	gcc -fdiagnostics-color=always -g map.c level.c agent.c drawGraph.c gameLogic.c gameManager.c main.c -o mainProgram -framework OpenGL -framework GLUT -Wno-deprecated-declarations

